### ISSUE TITLE
MESSAGE header confusion in 1.2 specification

### ISSUE THREAD

**Issue by ghost** [stomp/stomp-spec#80]
Hi!

What's the meaning of "If the message has been sent using STOMP, this destination header SHOULD be identical to the one used in the corresponding SEND frame."?

**Comment by LionelCons** [comment]
Messaging brokers can support different messaging protocols.

If STOMP is used both ways (to send the message and to receive it) then the "destination header SHOULD be identical to the one used in the corresponding SEND frame".

If another protocol is used to send the message then this does not apply since the destination might be coded differently. We could for instance have a message sent using a destination of `queue://foo` and received via STOMP in a `MESSAGE` frame with a `destination` header of `/queue/foo`.
